### ISSUE TITLE
Errors executing even the first "SELECT" statement

### ISSUE THREAD

**Issue by ankush981** [herrfugbaum/qsv#13]
So I ran the tool against the StackOverflow Survey Results CSV (28 MB file) that looks like this:

![data](https://user-images.githubusercontent.com/4169691/49155130-30623880-f340-11e8-9362-94708b0b534a.png)

And then when I try to run qsv I get the following errors:

```
qsv$ node bin/qsv.js -p "/home/ankush/Desktop/data.csv" -h
QSV> select * from table;
Lexing Errors detected.
unexpected character: ->;<- at offset: 19, skipped 1 characters.
QSV> Select * from table;
Lexing Errors detected.
unexpected character: ->;<- at offset: 19, skipped 1 characters.
QSV> SELECT * from table;
Lexing Errors detected.
unexpected character: ->;<- at offset: 19, skipped 1 characters.
QSV> SELECT * from Table
Parsing errors detected!
Expecting token of type --> From <-- but found --> 'from' <--
QSV> SELECT * from table
Parsing errors detected!
Expecting token of type --> From <-- but found --> 'from' <--
QSV> qsv$ node bin/qsv.js -p "/home/ankush/Desktop/data.csv" -h
QSV> select * from table;
Lexing Errors detected.
unexpected character: ->;<- at offset: 19, skipped 1 characters.
```
I'm at a loss to understand why even the basic "SELECT" statement is not being accepted. I've tried several variations, as evident in the snippet, but something seems to be stuck somewhere. 

How to resolve this? Happy to provide more info if needed.

**Comment by herrfugbaum** [comment]
This happens because the parser doesn't understand much yet.

To make it work try:

```sql
SELECT * FROM table
```

Note: All keywords are uppercase and no semicolon.

**Comment by ankush981** [comment]
Ah. Cool, thanks!
