### ISSUE TITLE
Make the parser case-insensitive

### ISSUE THREAD

**Issue by ankush981** [herrfugbaum/qsv#24]
I would really like the convenience of not having to reach for the Shift key when typing keywords. `select * from table` seems as legit to me as `SELECT * FROM table` does. And maybe I'm wrong, but I feel that this should be a simple matter of applying lowercase functions to the keywords (tokens?).

**Comment by herrfugbaum** [comment]
I have added case insensitivity to the parser already, I just forgot to update the dependency here as it seems 😅

Support for semicolon still needs to be added. Would you add it as a mandatory character or as an optinal one?

If we head for a non interactive mode it could come in handy to have a terminator in place to support multiple statements at once.
